import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { enableAutoUnmount, flushPromises, mount } from '@vue/test-utils'
import ImageStudioView from '../ImageStudioView.vue'

enableAutoUnmount(fn => afterEach(() => { fn(); vi.useRealTimers(); vi.unstubAllGlobals(); vi.restoreAllMocks() }))
const mocks = vi.hoisted(() => ({ keys: vi.fn(), models: vi.fn(), tasks: vi.fn(), submit: vi.fn(), image: vi.fn(), copy: vi.fn(), user: { id: 7 } }))
vi.mock('@/api/keys', () => ({ keysAPI: { list: mocks.keys } }))
vi.mock('@/api/client', () => ({ buildGatewayUrl: (path: string) => path }))
vi.mock('@/api/imageStudio', async importOriginal => ({
  ...await importOriginal<typeof import('@/api/imageStudio')>(),
  listStudioModels: mocks.models, listStudioTasks: mocks.tasks, submitStudioTask: mocks.submit, fetchStudioImage: mocks.image,
  studioCapabilities: () => ({ quality: true, resolutions: ['1K'] }),
}))
vi.mock('@/stores/app', () => ({ useAppStore: () => ({ showSuccess: vi.fn() }) }))
vi.mock('@/stores/auth', () => ({ useAuthStore: () => ({ user: mocks.user }) }))
vi.mock('@/composables/useClipboard', () => ({ useClipboard: () => ({ copyToClipboard: mocks.copy }) }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/components/layout/AppLayout.vue', () => ({ default: { template: '<main><slot /></main>' } }))

function view() { return mount(ImageStudioView, { global: { stubs: { RouterLink: { template: '<a><slot /></a>' }, Icon: true } } }) }
beforeEach(() => {
  vi.clearAllMocks()
  sessionStorage.clear()
  mocks.user.id = 7
  mocks.keys.mockResolvedValue({ items: [1, 2].map(id => ({ id, key: `secret-${id}`, name: `key-${id}`, status: 'active', quota: 0, group: { name: `group-${id}`, platform: 'openai', allow_image_generation: true } })), pages: 1 })
  mocks.models.mockResolvedValue(['gpt-image-2'])
  mocks.tasks.mockResolvedValue({ data: [], enabled: true })
  mocks.image.mockResolvedValue(new Blob(['original'], { type: 'image/png' }))
})

function previewTask() {
  return { id: 'preview-task', status: 'completed', created_at: Date.now() / 1000, expires_at: Date.now() / 1000 + 7200,
    request: { prompt: 'A landscape', model: 'gpt-image-2' },
    result: { data: [{ url: '/v1/images/assets/original', preview_url: '/v1/images/assets/preview' }] } }
}

describe('ImageStudioView', () => {
  it('loads only the small preview until download, retaining an in-flight download across polls', async () => {
    vi.useFakeTimers({ toFake: ['setInterval', 'clearInterval', 'Date'] })
    const original = new Blob(['full resolution original'], { type: 'image/png' })
    const createURL = vi.fn((blob: Blob) => blob.type === 'image/jpeg' ? 'blob:preview' : 'blob:original')
    vi.stubGlobal('URL', { createObjectURL: createURL, revokeObjectURL: vi.fn() })
    const click = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    let finishOriginal!: (blob: Blob) => void
    mocks.image.mockImplementation((_key: string, path: string) => path.endsWith('/preview')
      ? Promise.resolve(new Blob(['small'], { type: 'image/jpeg' }))
      : new Promise(resolve => { finishOriginal = resolve }))
    // Polling returns fresh task objects, just as a real JSON response does.
    mocks.tasks.mockImplementation(async () => ({ enabled: true, data: [previewTask()] }))
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    expect(wrapper.get('.preview img').attributes('src')).toBe('blob:preview')
    expect(mocks.image).toHaveBeenCalledTimes(1)
    expect(mocks.image).toHaveBeenLastCalledWith('secret-1', '/v1/images/assets/preview', expect.any(AbortSignal))
    await wrapper.get('.result-actions .btn-primary').trigger('click')
    expect(wrapper.get('.result-actions .btn-primary').text()).toContain('imageStudio.loadingOriginal')
    expect(wrapper.get('.result-actions .btn-primary').attributes('disabled')).toBeDefined()
    expect(mocks.image).toHaveBeenLastCalledWith('secret-1', '/v1/images/assets/original', expect.any(AbortSignal))
    await vi.advanceTimersByTimeAsync(12000)
    await flushPromises()
    expect(mocks.image).toHaveBeenCalledTimes(2)
    expect(mocks.image.mock.calls[1]![2].aborted).toBe(false)
    finishOriginal(original)
    await flushPromises()
    expect(createURL).toHaveBeenCalledWith(original)
    expect(click).toHaveBeenCalledTimes(1)
    const link = click.mock.instances[0] as HTMLAnchorElement
    expect(link.href).toBe('blob:original')
    expect(link.download).toBe('preview-task-1.png')
    await wrapper.get('.result-actions .btn-primary').trigger('click')
    await flushPromises()
    expect(mocks.image).toHaveBeenCalledTimes(2)
    expect(click).toHaveBeenCalledTimes(2)
    wrapper.unmount()
    expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:preview')
    expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:original')
  })

  it('aborts and discards an old original download when changing keys', async () => {
    vi.stubGlobal('URL', { createObjectURL: () => 'blob:preview', revokeObjectURL: vi.fn() })
    const click = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    let finishOriginal!: (blob: Blob) => void
    mocks.image.mockImplementation((_key: string, path: string) => path.endsWith('/preview')
      ? Promise.resolve(new Blob(['small'], { type: 'image/jpeg' }))
      : new Promise(resolve => { finishOriginal = resolve }))
    mocks.tasks.mockImplementation(async (key: string) => ({ enabled: true, data: key === 'secret-1' ? [previewTask()] : [] }))
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    await wrapper.get('.result-actions .btn-primary').trigger('click')
    const signal = mocks.image.mock.calls[1]![2] as AbortSignal
    await wrapper.get('#studio-key').setValue('2')
    await flushPromises()
    expect(signal.aborted).toBe(true)
    finishOriginal(new Blob(['old original'], { type: 'image/png' }))
    await flushPromises()
    expect(click).not.toHaveBeenCalled()
    expect(wrapper.find('.preview img').exists()).toBe(false)
  })

  it('uses original bytes for a reference instead of the reduced preview', async () => {
    vi.stubGlobal('URL', { createObjectURL: () => 'blob:preview', revokeObjectURL: vi.fn() })
    const original = new Blob(['full resolution original'], { type: 'image/png' })
    mocks.image.mockImplementation(async (_key: string, path: string) => path.endsWith('/preview') ? new Blob(['small'], { type: 'image/jpeg' }) : original)
    mocks.tasks.mockResolvedValue({ enabled: true, data: [previewTask()] })
    mocks.submit.mockResolvedValue({ id: 'next', status: 'processing', expires_at: Date.now() / 1000 + 7200 })
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    await wrapper.get('.result-actions .btn-secondary').trigger('click')
    await flushPromises()
    expect(mocks.image).toHaveBeenLastCalledWith('secret-1', '/v1/images/assets/original', expect.any(AbortSignal))
    await wrapper.get('.generate-button').trigger('click')
    await flushPromises()
    const reference = mocks.submit.mock.calls[0]![1].reference as File
    expect(reference.size).toBe(original.size)
    expect(reference.type).toBe('image/png')
  })

  it('falls back to the original when the optional preview is unavailable', async () => {
    vi.stubGlobal('URL', { createObjectURL: () => 'blob:original', revokeObjectURL: vi.fn() })
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    mocks.image.mockImplementation(async (_key: string, path: string) => {
      if (path.endsWith('/preview')) throw new Error('HTTP 404')
      return new Blob(['original'], { type: 'image/png' })
    })
    mocks.tasks.mockResolvedValue({ enabled: true, data: [previewTask()] })
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    expect(wrapper.get('.preview img').attributes('src')).toBe('blob:original')
    expect(wrapper.text()).not.toContain('HTTP 404')
    await wrapper.get('.result-actions .btn-primary').trigger('click')
    await flushPromises()
    expect(mocks.image).toHaveBeenCalledTimes(2)
  })

  it('keeps a preview visible and allows retry after an original download fails', async () => {
    vi.stubGlobal('URL', { createObjectURL: () => 'blob:preview', revokeObjectURL: vi.fn() })
    const click = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    mocks.image.mockImplementation(async (_key: string, path: string) => {
      if (path.endsWith('/original')) throw new Error('HTTP 503')
      return new Blob(['small'], { type: 'image/jpeg' })
    })
    mocks.tasks.mockResolvedValue({ enabled: true, data: [previewTask()] })
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    await wrapper.get('.result-actions .btn-primary').trigger('click')
    await flushPromises()
    expect(wrapper.get('.preview img').attributes('src')).toBe('blob:preview')
    expect(wrapper.text()).toContain('HTTP 503')
    expect(wrapper.get('.result-actions .btn-primary').attributes('disabled')).toBeUndefined()
    expect(click).not.toHaveBeenCalled()
    mocks.image.mockResolvedValue(new Blob(['original'], { type: 'image/png' }))
    await wrapper.get('.result-actions .btn-primary').trigger('click')
    await flushPromises()
    expect(click).toHaveBeenCalledTimes(1)
    expect(wrapper.text()).not.toContain('HTTP 503')
  })

  it('keeps the preview and saved prompt without result parameter comparisons', async () => {
    vi.stubGlobal('URL', { createObjectURL: () => 'blob:preview', revokeObjectURL: vi.fn() })
    mocks.image.mockResolvedValue(new Blob(['image'], { type: 'image/png' }))
    mocks.tasks.mockResolvedValue({ enabled: true, data: [{ id: '4k-task', status: 'completed', created_at: Date.now() / 1000, expires_at: Date.now() / 1000 + 7200, request: { prompt: 'A portrait', model: 'gpt-image-2', size: '3840x2160', quality: 'high' }, result: { quality: 'auto', data: [{ url: '/v1/images/assets/test', width: 1145, height: 1374, size: '1145x1374' }] } }] })
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    expect(wrapper.get('.preview img').attributes('src')).toBe('blob:preview')
    expect(wrapper.get('.saved-prompt').text()).toContain('A portrait')
    expect(wrapper.find('.output-details').exists()).toBe(false)
    expect(wrapper.find('.output-mismatch').exists()).toBe(false)
    expect(wrapper.find('.output-quality-mismatch').exists()).toBe(false)
    await wrapper.get('.settings-trigger').trigger('click')
    await wrapper.get('#studio-ratio').setValue('1:1')
    expect(wrapper.find('#studio-properties').exists()).toBe(true)
    expect(wrapper.find('.output-details').exists()).toBe(false)
    await wrapper.get('.history-button').trigger('click')
    expect(wrapper.get('.history-dimensions').text()).toContain('3840 × 2160')
    expect(wrapper.get('.history-dimensions').text()).toContain('1145 × 1374')
  })
  it('revokes an expired image preview and removes it from history', async () => {
    vi.useFakeTimers({ toFake: ['setInterval', 'clearInterval', 'Date'] })
    const revoke = vi.fn()
    vi.stubGlobal('URL', { createObjectURL: () => 'blob:preview', revokeObjectURL: revoke })
    mocks.image.mockResolvedValue(new Blob(['image'], { type: 'image/png' }))
    mocks.tasks.mockResolvedValue({ enabled: true, data: [{ id: 'task-1', status: 'completed', created_at: Date.now() / 1000, expires_at: Math.floor(Date.now() / 1000) + 2, request: { prompt: 'Expiring prompt', model: 'gpt-image-2' }, result: { data: [{ url: '/v1/images/assets/test' }] } }] })
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    expect(wrapper.find('.preview img').exists()).toBe(true)
    expect(wrapper.get('.saved-prompt').text()).toContain('Expiring prompt')
    await vi.advanceTimersByTimeAsync(3000)
    await flushPromises()
    expect(wrapper.find('.preview img').exists()).toBe(false)
    expect(wrapper.find('.saved-prompt').exists()).toBe(false)
    expect(revoke).toHaveBeenCalledWith('blob:preview')
    await wrapper.get('.history-button').trigger('click')
    expect(wrapper.findAll('.history-list button')).toHaveLength(0)
    wrapper.unmount()
  })

  it('requires a key and prompt; prompt cards retain key and model selection', async () => {
    const wrapper = view()
    await flushPromises()
    expect(wrapper.get('.generate-button').attributes('disabled')).toBeDefined()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    await wrapper.get('.prompt-card').trigger('click')
    expect((wrapper.get('#studio-key').element as HTMLSelectElement).value).toBe('1')
    expect((wrapper.get('#studio-model').element as HTMLSelectElement).value).toBe('gpt-image-2')
    expect(wrapper.get('.generate-button').attributes('disabled')).toBeUndefined()
    expect(mocks.submit).not.toHaveBeenCalled()
  })

  it('discards the previous key’s late model response and never submits a stale model', async () => {
    let resolveFirst!: (models: string[]) => void
    mocks.models.mockImplementation((key: string) => key === 'secret-1' ? new Promise(resolve => { resolveFirst = resolve }) : Promise.resolve(['gpt-image-2.5-flare']))
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await wrapper.get('#studio-key').setValue('2')
    await flushPromises()
    resolveFirst(['gpt-image-2'])
    await flushPromises()
    expect(wrapper.get('#studio-model').text()).not.toContain('gpt-image-2\n')
    expect((wrapper.get('#studio-model').element as HTMLSelectElement).value).toBe('gpt-image-2.5-flare')
    expect(mocks.tasks).toHaveBeenCalledWith('secret-2', expect.any(AbortSignal))
  })

  it('keeps generation disabled when no model or storage is available', async () => {
    mocks.models.mockResolvedValue([])
    mocks.tasks.mockResolvedValue({ data: [], enabled: false })
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await wrapper.get('#studio-prompt').setValue('A tree')
    await flushPromises()
    expect(wrapper.get('.generate-button').attributes('disabled')).toBeDefined()
    expect(wrapper.text()).toContain('imageStudio.noModels')
    expect(wrapper.text()).toContain('imageStudio.unavailable')
  })

  it('restores a running task after leaving the page, then refreshes completed history and copies its prompt', async () => {
    vi.useFakeTimers({ toFake: ['setInterval', 'clearInterval', 'Date'] })
    const task = { id: 'running', status: 'processing', created_at: Date.now() / 1000, expires_at: Date.now() / 1000 + 7200, request: { prompt: 'A cat\nunder the stars', model: 'gpt-image-2' } }
    mocks.submit.mockResolvedValue(task)
    const first = view()
    await flushPromises()
    await first.get('#studio-key').setValue('2')
    await flushPromises()
    await first.get('#studio-prompt').setValue(task.request.prompt)
    await first.get('.generate-button').trigger('click')
    await flushPromises()
    first.unmount()
    mocks.tasks.mockResolvedValue({ data: [task], enabled: true })
    const restored = view()
    await flushPromises()
    expect((restored.get('#studio-key').element as HTMLSelectElement).value).toBe('2')
    expect(restored.text()).toContain('imageStudio.generating')
    expect((restored.get('#studio-prompt').element as HTMLTextAreaElement).value).toBe(task.request.prompt)
    expect(JSON.stringify(sessionStorage)).not.toContain('secret-2')
    expect(JSON.stringify(sessionStorage)).not.toContain(task.request.prompt)
    mocks.tasks.mockResolvedValue({ data: [{ ...task, status: 'completed' }], enabled: true })
    await restored.get('.history-button').trigger('click')
    await flushPromises()
    expect(restored.get('.history-item').text()).toContain('imageStudio.completed')
    expect(restored.get('.history-prompt').text()).toContain('under the stars')
    await restored.get('.history-item .prompt-actions button').trigger('click')
    expect(mocks.copy).toHaveBeenCalledWith(task.request.prompt)
    await restored.get('#studio-prompt').setValue('Different draft')
    await restored.findAll('.history-item .prompt-actions button')[1]!.trigger('click')
    expect((restored.get('#studio-prompt').element as HTMLTextAreaElement).value).toBe(task.request.prompt)
    expect(mocks.submit).toHaveBeenCalledTimes(1)
    restored.unmount()
  })

  it('does not restore another user’s selection or show a fetch error as empty history', async () => {
    sessionStorage.setItem('image-studio-selection:99', JSON.stringify({ keyID: '2', selections: {} }))
    mocks.tasks.mockRejectedValue(new Error('History unavailable'))
    const wrapper = view()
    await flushPromises()
    expect((wrapper.get('#studio-key').element as HTMLSelectElement).value).toBe('')
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    await wrapper.get('.history-button').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('History unavailable')
    expect(wrapper.text()).not.toContain('imageStudio.noHistory')
  })

  it('offers ten ratios and custom dimensions, rejects invalid dimensions before submitting', async () => {
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    await wrapper.get('#studio-prompt').setValue('A landscape')
    await wrapper.get('.settings-trigger').trigger('click')
    expect(wrapper.findAll('#studio-ratio option')).toHaveLength(11)
    await wrapper.get('#studio-ratio').setValue('21:9')
    expect(wrapper.get('.ratio-description').text()).toContain('21_9')
    await wrapper.get('#studio-ratio').setValue('custom')
    await wrapper.get('#studio-width').setValue('0')
    expect(wrapper.get('.generate-button').attributes('disabled')).toBeDefined()
    await wrapper.get('#studio-width').setValue('1234')
    await wrapper.get('#studio-height').setValue('987')
    mocks.submit.mockResolvedValue({ id: 'custom', status: 'processing', expires_at: Date.now() / 1000 + 7200 })
    await wrapper.get('.generate-button').trigger('click')
    await flushPromises()
    expect(mocks.submit).toHaveBeenCalledWith('secret-1', expect.objectContaining({ ratio: 'custom', width: 1234, height: 987 }))
  })

  it('a stale history response cannot erase a newly submitted task', async () => {
    let resolveHistory!: (result: unknown) => void
    const wrapper = view()
    await flushPromises()
    await wrapper.get('#studio-key').setValue('1')
    await flushPromises()
    mocks.tasks.mockImplementationOnce(() => new Promise(resolve => { resolveHistory = resolve }))
    await wrapper.get('.history-button').trigger('click')
    mocks.submit.mockResolvedValue({ id: 'new', status: 'processing', expires_at: Date.now() / 1000 + 7200 })
    await wrapper.get('#studio-prompt').setValue('Cat')
    await wrapper.get('.generate-button').trigger('click')
    await flushPromises()
    resolveHistory({ data: [], enabled: true })
    await flushPromises()
    expect(wrapper.text()).toContain('imageStudio.generatingHint')
  })

  it('discovers a submission accepted after the page was left, even when initial history was empty', async () => {
    vi.useFakeTimers({ toFake: ['setInterval', 'clearInterval', 'Date'] })
    sessionStorage.setItem('image-studio-selection:7', JSON.stringify({ keyID: '1', selections: {} }))
    const wrapper = view()
    await flushPromises()
    expect(wrapper.text()).toContain('imageStudio.emptyTitle')
    mocks.tasks.mockResolvedValue({ data: [{ id: 'late', status: 'processing', created_at: Date.now() / 1000, expires_at: Date.now() / 1000 + 7200, request: { prompt: 'Accepted after navigation', model: 'gpt-image-2' } }], enabled: true })
    await vi.advanceTimersByTimeAsync(4000)
    await flushPromises()
    expect(wrapper.text()).toContain('imageStudio.generatingHint')
    expect(wrapper.get('.saved-prompt').text()).toContain('Accepted after navigation')
    wrapper.unmount()
  })
})
